### ISSUE TITLE
How to set correct type according to the error message

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/api#3434]
I have some problems in a subquery project that depends on Polkadot-js API, seems that it may be a type issue, but I am not confirmed. @jacogr  Could you please take a look at it?

Below is the error log:

> subquery-node_1   | 2021-04-25T02:43:33.042Z <indexer> ERROR failed to fetch block Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 73, in Ed25519, Sr25519, Ecdsa

As the log display, I have checked the SignedBlock type between Polkadot-js API dependence to the project version and the actual types we provided.

> subquery project depends on the  Polkadot-js version: 4.5.1

```ts
export interface SignedBlock extends SignedBlockWithJustifications {
}

export interface SignedBlockWithJustifications extends Struct {
    readonly block: Block;
    readonly justifications: Option<Justifications>;
}

export interface Justifications extends Vec<Justification> {
}

export interface Justification extends ITuple<[ConsensusEngineId, EncodedJustification]> {
}

export interface ConsensusEngineId extends GenericConsensusEngineId {
}

export interface EncodedJustification extends Bytes {
}
```

> In provide project (polkadot-js version: 3.6.4). the repo is [here](https://github.com/darwinia-network/darwinia.js)

```ts
export interface SignedBlock extends Struct {
    readonly block: Block;
    readonly justification: Justification;
}

export interface Justification extends Bytes {
}
```

so I tried to patch provided version to consist of the dependence version, something like this:

```YAML
...
    SignedBlock: SignedBlockWithJustifications
    SignedBlockWithJustifications: 
        block: Block
        justifications: Option<Justifications>
    Justifications: Vec<Justification>
    Justification: (ConsensusEngineId, EncodedJustification)
    EncodedJustification: Bytes
...
```

Unfortunately, the SignedBlock type error seems not fixed. So, I have no idea how to fix this issue.
