### ISSUE TITLE
Error while generating interface defs via polkadot-types-from-defs

### ISSUE THREAD

**Issue by ipapandinas** [polkadot-js/api#5543]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Following up on issues #4837 & #5183; I am getting a similar error while trying to generate via metadata:

```bash
Error: TypeDefInfo.Enum: Parameter formatting not implemented on {"info":4,"type":"{\"_enum\":{\"Noop\":\"Null\",\"Set\":\"TernoaPalletsPrimitivesCommonCompoundFee\",\"Remove\":\"Null\"}}","sub":[{"info":10,"name":"Noop","type":"Null","index":0},{"info":10,"name":"Set","type":"TernoaPalletsPrimitivesCommonCompoundFee","index":1},{"info":10,"name":"Remove","type":"Null","index":2}]}
```

Here is the enum type quoted in the error message (extracted from the chain metadata):

```yaml
...
{
  id: 96
  type: {
    path: [
      ternoa_pallets_primitives
      common
      CompoundFee
    ]
    params: [
      {
        name: Balance
        type: 6
      }
    ]
    def: {
      Variant: {
        variants: [
          {
            name: Flat
            fields: [
              {
                name: null
                type: 6
                typeName: Balance
                docs: []
              }
            ]
            index: 0
            docs: []
          }
          {
            name: Percentage
            fields: [
              {
                name: null
                type: 89
                typeName: Permill
                docs: []
              }
            ]
            index: 1
            docs: []
          }
        ]
      }
    }
    docs: []
  }
}
...
```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

I am using the lastest `@polkadot/api` & `@polkadot/typegen` packages: v10.1.3.

Chain WSS endpoint: wss://mainnet.ternoa.network
Link to repository: [@ternoa/types](https://github.com/capsule-corp-ternoa/ternoa-js/tree/v2/packages/types)

  - Version:
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

My package.json:

```json
{
  "name": "@ternoa/types",
  "version": "0.0.1",
  "description": "Ternoa types using @polkadot/typegen to generate type definitions",
  "main": "index.js",
  "repository": "https://github.com/capsule-corp-ternoa/ternoa-js/packages/types",
  "license": "Apache-2.0",
  "publishConfig": {
    "access": "public",
    "directory": "src",
    "registry": "https://registry.npmjs.org"
  },
  "bugs": {
    "url": "https://github.com/capsule-corp-ternoa/ternoa-js/issues"
  },
  "homepage": "https://github.com/capsule-corp-ternoa/ternoa-js",
  "scripts": {
    "get-metadata": "ts-node get-metadata.ts",
    "build": "tsc && cp ./README.md ./build",
    "generate": "yarn generate:defs && yarn generate:meta",
    "generate:defs": "ts-node --skip-project node_modules/.bin/polkadot-types-from-defs --package @ternoa/types/interfaces --input ./src/interfaces  --endpoint ./ternoa.json",
    "generate:meta": "ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package @ternoa/types/interfaces --endpoint ./ternoa.json --output ./src/interfaces --strict",
    "lint": "tsc --noEmit --pretty"
  },
  "dependencies": {
    "@polkadot/api": "10.1.3"
  },
  "devDependencies": {
    "@polkadot/typegen": "10.1.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"
  }
}
```

My tsconfig.json:

```json
{
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "build",
    "target": "es2015",
    "module": "commonjs",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "moduleResolution": "node",
    "paths": {
      "@ternoa/types/*": ["src/*"],
      "@polkadot/api/augment": ["src/interfaces/augment-api.ts"],
      "@polkadot/types/augment": ["src/interfaces/augment-types.ts"]
    },
    "jsx": "preserve",
    "strict": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["**/*.ts"],
  "exclude": ["build/**/*", "node_modules"]
}
```
